## Asmaa Alzahrani
 8/11/2021


Week 5, Assignment C1:
Logistic Regression with Yahoo! Finance API in Python

In this notebook, we will study Logistic Regression using the Yahoo! Finance API in Python.

Please complete the lines bellow where you see "#TODO".

In [1]:
#Objective 1.
#Use this cell to import the Numpy (as np), Pandas (as pd), and YFinance (as yf) packages.


import numpy as np
import pandas as pd
import pandas
import yfinance as yf


#Our work will also require some components of the Sklearn and Pandas_Datareader packages as imported below:
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from pandas_datareader import data as pdr
yf.pdr_override()

In [2]:
#Objective 2.
#Select a stock symbol for a stock whose historical data is available on the Yahoo! Finance website.  Store the
#string of your chosen symbol to the new variable "stock_symbol".

stock_symbol = "LCID"


In [3]:
df = pdr.get_data_yahoo(stock_symbol, pandas.Timestamp('2019'), pandas.Timestamp('2021'))

[*********************100%***********************]  1 of 1 completed


In [4]:
#Objective 3.
#Use the function "pdr.get_data_yahoo(stock_symbol, start_date, end_date)" to generate a Pandas dataframe of
#historical stock data for your chosen stock.  Retain only the first four columns of the dataframe.  Be sure to 
#drop any rows containing NaN's, and take a peek at the resulting dataframe to make sure everything looks good.

df = pdr.get_data_yahoo(stock_symbol, pandas.Timestamp('2019'), pandas.Timestamp('2021'))
df = df[pdr.get_data_yahoo(stock_symbol, pandas.Timestamp('2019'), pandas.Timestamp('2021')).columns[0:4]]
df = df[['Open', 'High','Low','Close']]
df =df.dropna()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [5]:
df

Open    High    Low  Close
Date                                   
2020-09-18  10.25  10.250   9.82   9.89
2020-09-21   9.90   9.960   9.86   9.86
2020-09-22   9.96   9.960   9.85   9.88
2020-09-23   9.90   9.905   9.79   9.85
2020-09-24   9.85   9.850   9.75   9.77
...           ...     ...    ...    ...
2020-12-24  10.08  10.100  10.01  10.04
2020-12-28  10.11  10.180  10.04  10.08
2020-12-29  10.10  10.110  10.03  10.06
2020-12-30  10.04  10.080  10.02  10.07
2020-12-31  10.07  10.070  10.01  10.01

[73 rows x 4 columns]

In [6]:
#Objective 4.
#Use the historical data to define some predictor variables.  Add these variables to the dataframe.  Include, at a
#minimum, (Predictor.I) the rolling average closing price over the past fifteen (15) days and (Predictor.II) the
#change in opening price over the past one (1) day.  Be sure to again drop any rows containing NaN's, and take a
#peek at the resulting dataframe to make sure everything looks good.  Store the dataframe as the new variable "X".

df['Close_15_Rolling'] = df['Close'].rolling(window=15).mean()
df['Open_1_Change'] = df['Open'].diff()
df = df.dropna()
X = df

In [7]:
np.where([True,False,True,False],-1,1)

array([-1,  1, -1,  1])

In [8]:
#Objective 5.
#Define the target or dependent variable to be one (1) if the change in closing price over the past one (1) day is
#nonnegative and negative one (-1) if the change in closing price over the past one (1) day is negative.  This
#variable's values should be forward-looking (i.e., you should subtract today's price from tomorrow's price rather
#than subtracting yesterday's price from today's price).  Store the resulting values as the new variable "y".  You
#may find the "np.where(*args)" function to be useful.  Look it up in Numpy documentation for support.

y = np.where(
    (df.Close.shift(-1)-df['Close'])>=0
               ,
               1,
               -1)
print((df.Close.shift(-1)-df['Close'])[0:6])
y

Date
2020-10-08    0.033
2020-10-09   -0.020
2020-10-12   -0.030
2020-10-13   -0.020
2020-10-14    0.000
2020-10-15    0.000
Name: Close, dtype: float64


array([ 1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1,
        1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1, -1,  1, -1,  1,  1, -1, -1,  1, -1,  1,
        1,  1,  1,  1, -1,  1, -1, -1])

In [9]:
#Objective 6.
#Split the data into training and test sets, putting the first seventy percent (70%) of the data in the training
#set.

index = int(0.7*len(X))
X_train = X[:index]
X_test  = X[index:]
y_train = y[:index]
y_test  = y[index:]



In [10]:
#Objective 7.
#Instantiate the Logistic Regression model object, and use its ".fit(*args)" method to fit the model to the 
#training data.

logistic = LogisticRegression()
logistic = logistic.fit(X_train,y_train)

In [11]:
#Objective 8.
#Examine the model's coefficients by using its ".coef_" method.

pd.DataFrame({'column':X.columns.values, 'b':logistic.coef_.ravel()})

column         b
0              Open -0.069856
1              High -0.085211
2               Low  0.093167
3             Close  0.091455
4  Close_15_Rolling  0.027074
5     Open_1_Change -0.031182

In [12]:
#Objective 9.
#Use the model's ".predict_proba(*args)" and ".predict(*args)" methods to generate predictions over the test set.

probabilities = logistic.predict_proba(X_test)
predictions =  logistic.predict(X_test)

In [13]:
probabilities

array([[0.36350803, 0.63649197],
       [0.36740772, 0.63259228],
       [0.36402731, 0.63597269],
       [0.36381277, 0.63618723],
       [0.36344354, 0.63655646],
       [0.36201689, 0.63798311],
       [0.36421736, 0.63578264],
       [0.36267584, 0.63732416],
       [0.36279683, 0.63720317],
       [0.36223628, 0.63776372],
       [0.36216594, 0.63783406],
       [0.36302485, 0.63697515],
       [0.36142605, 0.63857395],
       [0.36336648, 0.63663352],
       [0.36370769, 0.63629231],
       [0.36246668, 0.63753332],
       [0.36046587, 0.63953413],
       [0.36284521, 0.63715479]])

In [14]:
#Objective 10.
#Use the function "metrics.confusion_matrix(*args)" to create a confusion matrix comparing the predicted and true
#classification labels over the test set.

sklearn.metrics.confusion_matrix(y_pred=predictions,y_true=y_test)

array([[ 0,  8],
       [ 0, 10]], dtype=int64)

In [15]:
#Objective 11.
#Calculate the model's accuracy on the test set using its ".score(*args)" method.

logistic.score(X_test,y_test)

0.5555555555555556

In [16]:
#Objective 12.
#Use five-fold cross validation to cross-check the accuracy of the model over different held-out test sets.  This
#is where you should use the function "cross_val_score(*args)".

#cross_val = #TODO
cross_val_score(logistic, X_test, y_test, cv=5)

array([0.5       , 0.5       , 0.5       , 0.66666667, 0.66666667])

# Thank you